//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepliesPublicConsultation
    {
        public int Id { get; set; }
        public Nullable<int> PublicConsultationId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProfessorId { get; set; }
        public string DateTime { get; set; }
        public string Motive { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual PublicConsultation PublicConsultation { get; set; }
        public virtual Student Student { get; set; }
    }
}
